//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fish", Namespace="http://schemas.datacontract.org/2004/07/JokeWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Fish : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFishService")]
    public interface IFishService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishService/GetFishes", ReplyAction="http://tempuri.org/IFishService/GetFishesResponse")]
        FishConsole.ServiceReference1.Fish[] GetFishes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishService/GetFishes", ReplyAction="http://tempuri.org/IFishService/GetFishesResponse")]
        System.Threading.Tasks.Task<FishConsole.ServiceReference1.Fish[]> GetFishesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishService/SaveFish", ReplyAction="http://tempuri.org/IFishService/SaveFishResponse")]
        void SaveFish(FishConsole.ServiceReference1.Fish fish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishService/SaveFish", ReplyAction="http://tempuri.org/IFishService/SaveFishResponse")]
        System.Threading.Tasks.Task SaveFishAsync(FishConsole.ServiceReference1.Fish fish);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFishServiceChannel : FishConsole.ServiceReference1.IFishService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FishServiceClient : System.ServiceModel.ClientBase<FishConsole.ServiceReference1.IFishService>, FishConsole.ServiceReference1.IFishService {
        
        public FishServiceClient() {
        }
        
        public FishServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FishServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FishServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FishServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FishConsole.ServiceReference1.Fish[] GetFishes() {
            return base.Channel.GetFishes();
        }
        
        public System.Threading.Tasks.Task<FishConsole.ServiceReference1.Fish[]> GetFishesAsync() {
            return base.Channel.GetFishesAsync();
        }
        
        public void SaveFish(FishConsole.ServiceReference1.Fish fish) {
            base.Channel.SaveFish(fish);
        }
        
        public System.Threading.Tasks.Task SaveFishAsync(FishConsole.ServiceReference1.Fish fish) {
            return base.Channel.SaveFishAsync(fish);
        }
    }
}
